wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.9
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700045700.003063
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 105
      3:
      - 23
      4: 3.7.9
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
